name: bitaniya_bible_study
description: Bitaniya Bible Study - complete redesigned Bible study journal.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_quill: 11.5.1

flutter:
  uses-material-design: true
